#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Core\Console\Cmd;

$app = new Application();

$console = new Cmd();
$app->add($console->register('ClearCache'));

$app->run();